name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Clear Docker Build cache
        run: docker builder prune -a -f

      - name: Write SSH key and set permissions
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      - name: SSH & Run Deployment Scripts
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            cd /var/www/Avocat
            
            # Mettre à jour le code
            git stash
            git pull origin main
            
            # Recréer le fichier .env si nécessaire (Optionnel - on suppose qu'il existe déjà sur le serveur)
            # Sinon on peut le générer à partir des secrets ici
            
            # Déploiement Docker
            docker compose down
            docker compose build --no-cache
            docker compose up -d
            
            # Ménage
            docker image prune -f
            
            echo '✅ Deployment successful'
          EOF
